# Generated by Django 3.0.1 on 2020-07-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200630_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createquestion',
            name='question_text',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='createquestion',
            name='title',
            field=models.CharField(default='Question', max_length=50),
        ),
    ]
